# Generated by Django 4.2.1 on 2023-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_managerment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.SmallIntegerField(choices=[(1, '超级管理员'), (2, '普通管理员')], default=2, verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
